/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package LinkeTinderAplication.app.Aplication

import java.util.Scanner

class App {
    static void main(String[] args) {
        (new TerminalUserInput()).runLoop()

    }
}
