/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package LinkeTinderAplication.app.Aplication

import LinkeTinderAplication.app.Aplication.Engine.Loop.AplicationLoop

class App {
    static void main(String[] args) {

        (new AplicationLoop()).runLoop()

    }
}
