/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package LinkeTinderAplication.app.Aplication

class App {
    static void main(String[] args) {

        //(new AplicationLoop()).runLoop()

    }
}
