CREATE TABLE CANDIDATO (
	ID			SERIAL		PRIMARY KEY,
	NOME			VARCHAR(255)	NOT NULL,
	SOBRE_NOME		VARCHAR(255)	NOT NULL,
	DATA_NASCIMENTO		DATE		NOT NULL,
	EMAIL			VARCHAR(255)	NOT NULL,
	CPF			VARCHAR(255)	NOT NULL,
	PAIS			VARCHAR(255)	NOT NULL,
	CEP			VARCHAR(255)	NOT NULL,
	DESC_PESSOAL		TEXT		,
	SENHA			VARCHAR(255)	NOT NULL
)

CREATE TABLE EMPRESA(
	ID			SERIAL		PRIMARY KEY,
	NOME			VARCHAR(255)	NOT NULL,
	CNPJ			VARCHAR(255)	NOT NULL,
	EMAIL			VARCHAR(255)	NOT NULL,
	DESCRICAO		TEXT		,
	PAIS 			VARCHAR(255)	NOT NULL,
	CEP			VARCHAR(255)	NOT NULL,
	SENHA			VARCHAR(255)	NOT NULL
)

CREATE TABLE COMPETENCIA(
	ID			SERIAL		PRIMARY KEY,
	TAG			VARCHAR(255)	NOT NULL
)

CREATE TABLE VAGA(
	ID			SERIAL		PRIMARY KEY,
	NOME			TEXT		NOT NULL,
	DESCRICAO		TEXT		NOT NULL,
	LOCAL			VARCHAR(255)	NOT NULL
)

CREATE TABLE COMPETENCIA_CANDIDATO(
	ID_CANDIDATO		SERIAL		REFERENCES CANDIDATO(ID),
	ID_COMPETENCIA		SERIAL		REFERENCES COMPETENCIA(ID),
	PRIMARY 		KEY		(ID_CANDIDATO,ID_COMPETENCIA)
)

CREATE TABLE COMPETENCIA_VAGA(
	ID_VAGA			SERIAL 		REFERENCES VAGA(ID),
	ID_COMPETENCIA		SERIAL		REFERENCES COMPETENCIA(ID),
	PRIMARY 		KEY		(ID_VAGA,ID_COMPETENCIA)
)

CREATE TABLE LIKE_CANDIDATO(
	ID_CANDIADTO		SERIAL		REFERENCES CANDIDATO(ID),
	ID_VAGA			SERIAL 		REFERENCES VAGA(ID),
	PRIMARY			KEY		(ID_CANDIADTO,ID_VAGA)
)

CREATE TABLE LIKE_EMPRESA(
	ID_CANDIADTO		SERIAL		REFERENCES CANDIDATO(ID),
	ID_EMPREASA		SERIAL 		REFERENCES VAGA(ID),
	PRIMARY			KEY		(ID_CANDIADTO,ID_EMPREASA)
)

CREATE TABLE EMPRESA_VAGA(
	ID_VAGA			SERIAL		REFERENCES VAGA(ID),
	ID_EMPREASA		SERIAL 		REFERENCES EMPRESA(ID),
	PRIMARY			KEY		(ID_VAGA,ID_EMPREASA)
)


